# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

# container_scanning:
#   variables:
#     DOCKER_IMAGE: ...
#     DOCKER_USER: ...
#     DOCKER_PASSWORD: ...
include:
- project: lc-templates/id_tokens
  file: id_tokens.yml
- template: Jobs/Container-Scanning.gitlab-ci.yml
stages:
- build
- test
".oslic":
  tags:
  - shell
  - oslic
before_script:
- python3 -m venv eye
- source eye/bin/activate
- pip3 install build
build:
  stage: build
  extends:
  - ".oslic"
  script:
  - python3 -m build
  artifacts:
    paths:
    - dist/
unittest:
  stage: test
  extends:
  - ".oslic"
  script:
  - ls
  - pip install dist/eyeon-*.whl
  - cd tests/
  - coverage run --source eyeon -m unittest testObserveRemote.py testParse.py testCli.py
    testBadSignatures.py testChecksum.py
  - coverage xml
  - coverage html
  - coverage report --precision=2
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  dependencies:
  - build
  artifacts:
    paths:
    - tests/htmlcov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml
