# Run workflow for both push and MR triggers, but avoid duplicate pipeline runs
# workflow:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#     - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
#       when: never
#     - if: '$CI_COMMIT_BRANCH'

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml # template for trivy scan
  - project: 'lc-templates/id_tokens'
    file: 'id_tokens.yml'

stages:
  - build
  - test
#   - sbom

.oslic:
  tags:
    - shell
    - oslic

before_script:
  - python3 -m venv eye  # Create venv
  - source eye/bin/activate
  - pip3 install build

build:
  stage: build
  extends:
    - .oslic
  script:
    - python3 -m build
  artifacts:
    paths:
      - dist/


trivy:  # Build project deps, download and install trivy, then scans filesystem
  stage: test
  extends:
    - .oslic
  dependencies:
    - build
  before_script:
    - pip install dist/eyeon-*.whl
    - apt-get update  # install requirements, and install LLNL CSP Certs
    - apt-get install -y wget ca-certificates apt-transport-https gnupg
    - wget "https://www-csp.llnl.gov/content/assets/csoc/cspca.crt" -O /usr/local/share/ca-certificates/cspca.crt
    - chmod 644 /usr/local/share/ca-certificates/cspca.crt && update-ca-certificates       

    # Install trivy
    - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null
    - echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | tee -a /etc/apt/sources.list.d/trivy.list
    - apt-get update
    - apt-get install -y trivy

  script:
    - trivy --version
	- time trivy clean --scan-cache --cache-dir .trivycache
    # make scan report and put it in the default workdir $CI_PROJECT_DIR, so 'artifacts:' can take it from there
    - time trivy --cache-dir .trivycache --format json --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" filesystem / 
  cache:
    paths:
      - .trivycache/
  # Enables https://docs.gitlab.com/ee/user/application_security/container_scanning/ (Container Scanning report is available on GitLab EE Ultimate or GitLab.com Gold)
  artifacts:
    when: always
    reports:
      container_scanning: gl-container-scanning-report.json


unittest:
  stage: test
  extends:
    - .oslic
  # image: python:3.10
  script:
    - ls
    - pip install dist/eyeon-*.whl
    - cd tests/
    - coverage run --source eyeon -m unittest testObserveRemote.py testParse.py testCli.py testChecksum.py
    - coverage xml
    - coverage html
    - coverage report --precision=2
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  dependencies:
    - build
  artifacts:
    paths:
      - 'tests/htmlcov/'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: 'tests/coverage.xml'


container_scanning: #extends the template
  extends:
    - .oslic
  variables:
    CS_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"  # container to be scanned by trivy, pushed in other job
    CS_REGISTRY_USER: "$CI_REGISTRY_USER"
    CS_REGISTRY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    CS_DOCKERFILE_PATH: "eyeon.Dockerfile"
    CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "false"  # tell trivy to scan pip packages 
    CS_SEVERITY_THRESHOLD: "UNKNOWN"  # set to UNKNOWN, LOW, MEDIUM, HIGH, CRITICAL
    # ^^^ scanner outputs vulns with severity higher than threshold. 
    SECURE_LOG_LEVEL: info
  before_script:
    - echo "${CI_REGISTRY_PASSWORD}" | podman login -u="$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  dependencies:
    - build

# sbom:  # put in artifacts instead
#   stage: sbom
#   script:
#     - cd .. # back to eyeon folder
#     - ./sbom-tool generate -b / -bc src/ -pn lsbom -pv 0.2 -ps "Lawrence Livermore National Laboratory" -nsb https://www.llnl.gov/
