# generated by datamodel-codegen:
#   filename:  observation.schema.json
#   timestamp: 2025-11-21T19:14:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Filetype(Enum):
    ELF = 'ELF'
    Malformed_PE = 'Malformed PE'
    DOS = 'DOS'
    Linux_Kernel_Image = 'Linux Kernel Image'
    PE = 'PE'
    OLE = 'OLE'
    MSCAB = 'MSCAB'
    ISCAB = 'ISCAB'
    DOCKER_GZIP = 'DOCKER_GZIP'
    GZIP = 'GZIP'
    BZIP2 = 'BZIP2'
    XZ = 'XZ'
    DOCKER_TAR = 'DOCKER_TAR'
    TAR = 'TAR'
    RAR = 'RAR'
    ZIP = 'ZIP'
    JAR = 'JAR'
    WAR = 'WAR'
    EAR = 'EAR'
    APK = 'APK'
    IPA = 'IPA'
    MSIX = 'MSIX'
    MACHOFAT = 'MACHOFAT'
    JAVACLASS = 'JAVACLASS'
    MACHOFAT_1 = 'MACHOFAT'
    MACHOFAT64 = 'MACHOFAT64'
    EFIFAT = 'EFIFAT'
    MACHO32 = 'MACHO32'
    MACHO64 = 'MACHO64'
    LLVM_BITCODE = 'LLVM_BITCODE'
    LLVM_IR = 'LLVM_IR'
    A_OUT_big = 'A.OUT big'
    A_OUT_little = 'A.OUT little'
    COFF = 'COFF'
    XCOFF32 = 'XCOFF32'
    XCOFF64 = 'XCOFF64'
    ECOFF = 'ECOFF'
    AR_LIB = 'AR_LIB'
    OMF_LIB = 'OMF_LIB'
    UIMAGE = 'UIMAGE'
    ZLIB = 'ZLIB'
    CPIO_BIN_big = 'CPIO_BIN big'
    CPIO_BIN_little = 'CPIO_BIN little'
    CPIO_ASCII_OLD = 'CPIO_ASCII_OLD'
    CPIO_ASCII_NEW = 'CPIO_ASCII_NEW'
    CPIO_ASCII_NEW_CRC = 'CPIO_ASCII_NEW_CRC'
    ZSTANDARD = 'ZSTANDARD'
    ZSTANDARD_DICTIONARY = 'ZSTANDARD_DICTIONARY'
    ISO_9660_CD = 'ISO_9660_CD'
    MACOS_DMG = 'MACOS_DMG'
    RPM_Package = 'RPM Package'


class ChecksumVerification(BaseModel):
    algorithm: str
    expected: str
    actual: str
    verified: bool


class Cert(BaseModel):
    sha256: Optional[str] = None
    issuer_sha256: Optional[str] = None
    cert__version: Optional[str] = Field(None, alias='cert._version')
    serial_number: Optional[str] = None
    issuer_name: Optional[str] = None
    subject_name: Optional[str] = None
    issued_on: Optional[str] = None
    expires_on: Optional[str] = None
    signed_using: Optional[str] = None
    RSA_key_size: Optional[str] = None
    basic_constraints: Optional[str] = None
    key_usage: Optional[str] = None
    ext_key_usage: Optional[str] = None
    certificate_policies: Optional[str] = None


class Certs(RootModel[list[Cert]]):
    root: list[Cert]


class AOUTMetadata(BaseModel):
    aoutMachineType: str


class CoffMetadata(BaseModel):
    coffMachineType: str


class CreationInfo(BaseModel):
    creators: Optional[list] = None
    created: Optional[str] = None


class Package(BaseModel):
    name: Optional[str] = None
    SPDXID: Optional[str] = None
    supplier: Optional[str] = None
    downloadLocation: Optional[str] = None
    filesAnalyzed: Optional[bool] = None
    licenseConcluded: Optional[str] = None


class File(BaseModel):
    fileName: Optional[str] = None
    SPDXID: Optional[str] = None
    checksums: Optional[list] = None
    licenseConcluded: Optional[str] = None
    copyrightText: Optional[str] = None
    comment: Optional[str] = None
    annotations: Optional[list] = None


class Relationship(BaseModel):
    spdxElementId: Optional[str] = None
    relatedSpdxElement: Optional[str] = None
    relationshipType: Optional[str] = None


class DockerSPDX(BaseModel):
    spdxVersion: Optional[str] = None
    dataLicense: Optional[str] = None
    SPDXID: Optional[str] = None
    name: Optional[str] = None
    documentNamespace: Optional[str] = None
    creationInfo: Optional[CreationInfo] = None
    packages: Optional[list[Package]] = None
    files: Optional[list[File]] = None
    relationships: Optional[list[Relationship]] = None


class DockerImageMetadata(BaseModel):
    dockerSPDX: DockerSPDX


class ElfIdent(BaseModel):
    EI_CLASS: Optional[int] = None
    EI_DATA: Optional[int] = None
    EI_VERSION: Optional[int] = None
    EI_OSABI: Optional[int] = None
    EI_ABIVERSION: Optional[int] = None
    E_MACHINE: Optional[int] = None


class ELFMetadata(BaseModel):
    OS: Optional[str] = None
    elfIdent: ElfIdent
    elfDependencies: list
    elfRpath: Optional[list] = None
    elfRunpath: Optional[list] = None
    elfSoname: Optional[list] = None
    elfInterpreter: Optional[list] = None
    elfDynamicFlags: Optional[list] = None
    elfDynamicFlags1: Optional[list] = None
    elfGnuRelro: Optional[bool] = None
    elfComment: Optional[list] = None
    elfNote: Optional[list] = None
    elfOsAbi: Optional[str] = None
    elfHumanArch: Optional[str] = None
    elfArchNumber: Optional[int] = None
    elfArchitecture: Optional[str] = None
    elfIsExe: Optional[bool] = None
    elfIsLib: Optional[bool] = None
    elfIsRel: Optional[bool] = None
    elfIsCore: Optional[bool] = None


class JavaMetadata(BaseModel):
    pass


class JavascriptMetadata(BaseModel):
    jsLibraries: list


class Header(BaseModel):
    cpuType: Optional[str] = None
    cpuTypeValue: Optional[int] = None
    cpuSubtype: Optional[str] = None
    cpuSubtypeValue: Optional[int] = None
    fileType: Optional[str] = None
    fileTypeValue: Optional[int] = None
    flags: Optional[list] = None
    numCommands: Optional[int] = None


class Tool(BaseModel):
    tool: Optional[str] = None
    version: Optional[str] = None


class Build(BaseModel):
    platform: Optional[str] = None
    platformValue: Optional[int] = None
    minOSVersion: Optional[str] = None
    sdkVersion: Optional[str] = None
    tools: Optional[list[Tool]] = None


class Signature1(BaseModel):
    offset: Optional[int] = None
    size: Optional[int] = None
    type: Optional[str] = None


class Dyld(BaseModel):
    linker: Optional[str] = None


class Binary(BaseModel):
    format: Optional[str] = None
    header: Optional[Header] = None
    build: Optional[Build] = None
    signature: Optional[Signature1] = None
    dependencies: Optional[list[Any]] = None
    rpaths: Optional[list[str]] = None
    dyld: Optional[Dyld] = None
    encryption: Optional[dict[str, Any]] = None


class MachOMetadata(BaseModel):
    OS: Optional[str] = None
    numBinaries: int
    binaries: list[Binary]


class NativeMetadata(BaseModel):
    nativeLibraries: list


class Ole(BaseModel):
    clsid: Optional[str] = None
    clsid_type: Optional[str] = None
    codepage: Optional[str] = None
    title: Optional[str] = None
    author: Optional[str] = None
    template: Optional[str] = None
    revision_number: Optional[str] = None
    last_printed: Optional[str] = None
    create_time: Optional[str] = None
    last_saved_time: Optional[str] = None
    num_pages: Optional[str] = None
    num_words: Optional[str] = None
    creating_application: Optional[str] = None
    security: Optional[str] = None


class OleMetadata(BaseModel):
    ole: Ole


class PEMetadata(BaseModel):
    OS: Optional[str] = None
    peMachine: str
    peOperatingSystemVersion: Optional[str] = None
    peSubsystemVersion: Optional[str] = None
    peSubsystem: Optional[str] = None
    peLinkerVersion: Optional[str] = None
    peImport: Optional[list[str]] = None
    peIsExe: Optional[bool] = None
    peIsDll: Optional[bool] = None
    peIsClr: Optional[bool] = None
    FileInfo: Optional[dict[str, Any]] = None
    dllRedirectionLocal: Optional[bool] = None


class Rpm(BaseModel):
    name: Optional[str] = None
    sourcerpm: Optional[str] = None
    version: Optional[str] = None
    release: Optional[str] = None
    summary: Optional[str] = None
    description: Optional[str] = None
    rpmversion: Optional[str] = None
    copyright: Optional[str] = None
    os: Optional[str] = None
    arch: Optional[str] = None
    target: Optional[str] = None
    archive_format: Optional[str] = None
    archive_compression: Optional[str] = None
    optflags: Optional[str] = None
    sha256: Optional[str] = None
    md5: Optional[str] = None
    requirename: Optional[dict[str, Any]] = None
    provides: Optional[dict[str, Any]] = None
    buildtime: Optional[int] = None
    associated_files: Optional[dict[str, Any]] = None


class RPMMetadata(BaseModel):
    rpm: Rpm


class UbootImageMetadata(BaseModel):
    uimage_header: dict[str, Any]


class OtherMetadata(BaseModel):
    description: str


class Signature(BaseModel):
    certs: Optional[Certs] = None
    signers: str
    digest_algorithm: str
    verification: Optional[str] = None
    sha1: Optional[str] = None


class ObservationModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bytecount: int = Field(..., description='Size of file in bytes')
    compiler: Optional[str] = Field(None, description='Compiler Identifier')
    filename: str = Field(..., description='Basename of file')
    filetype: Filetype = Field(
        ...,
        description='Specific file types recognized by EyeON. These are grouped together in the metadata definitions based on the properties they have in common',
    )
    imphash: Optional[str] = Field(
        None, description='Import Hash calculated via pefile'
    )
    telfhash: Optional[str] = Field(
        None, description='Import hashing technique used on ELF files'
    )
    magic: str = Field(..., description='`file` Magic output for given file')
    md5: str = Field(..., description='MD5 of file')
    modtime: Optional[str] = Field(None, description='Last modified date')
    observation_ts: str = Field(..., description='Date and time file was scanned')
    parent: Optional[str] = Field(
        None,
        description='Some yet-to-be-determined pointer to a parent file or something',
    )
    permissions: Optional[str] = Field(None, description='Permissions of file')
    sha1: str = Field(..., description='Sha1 of file')
    sha256: str = Field(..., description='Sha256 of file')
    ssdeep: Optional[str] = Field(None, description='Ssdeep of file')
    target_os: Optional[str] = Field(
        None, description='Operating system of target machine'
    )
    uuid: str = Field(..., description='Universally Unique Identifier')
    authentihash: Optional[str] = Field(
        None, description='Authentihash computed from signature hashing algorithm'
    )
    authenticode_integrity: Optional[str] = Field(
        None,
        description='Checks if signatures are OK and if digest matches hashed authenticode',
    )
    metadata: Optional[
        Union[
            AOUTMetadata,
            CoffMetadata,
            DockerImageMetadata,
            ELFMetadata,
            JavaMetadata,
            JavascriptMetadata,
            MachOMetadata,
            NativeMetadata,
            OleMetadata,
            PEMetadata,
            RPMMetadata,
            UbootImageMetadata,
            OtherMetadata,
        ]
    ] = None
    signatures: Optional[list[Signature]] = None
    checksum_verification: Optional[ChecksumVerification] = None
